#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

export TEMUXIS_CONFIG_PATH="${XDG_CONFIG_HOME:-$HOME/.config}/temuxis"
export TEMUXIS_SESSIONS_PATH="$TEMUXIS_CONFIG_PATH/sessions"

mkdir -p $TEMUXIS_CONFIG_PATH
mkdir -p $TEMUXIS_SESSIONS_PATH

cli_name='temuxis'
author='Emerson Max de Medeiros Silva'
version='1.0'

function cli_help() {
    echo "Usage: $cli_name [command]

TMUX session manager

commands:
    start      Start session
    edit       Edit a session
    list       List all available session
    help       Show this help
    version    Show version
"
}

if [[ $# < 1 ]]
then
    cli_help
    exit 1
fi

function start_cmd() {
    if [[ $# == 0 ]]
    then
        echo "Usage: $cli_name start <session>"
        exit 1
    fi

    session="$1"
    shift 1

    "$TEMUXIS_SESSIONS_PATH/$session" $@
}

function edit_cmd() {
    if [[ $# == 0 ]]
    then
        echo "Usage: $cli_name edit <session>"
        exit 1
    fi

    session="$1"
    session_path="$TEMUXIS_SESSIONS_PATH/$session"

    if [[ -z ${EDITOR+x} ]]
    then
        echo 'Variable $EDITOR has not been defined.'
        echo 'Using vi by default.'
        EDITOR='vi'
    fi

    $EDITOR $session_path
}

function list_cmd() {
    for session_path in $TEMUXIS_SESSIONS_PATH/*
    do
        if [[ !(-x "$session_path" && -f "$session_path") ]]
        then
            continue
        fi

        session=$(basename $session_path)
        echo $session
    done
}

function help_cmd() {
    cli_help
    exit 0
}

function version_cmd() {
    echo "$cli_name $version"
}

action="$1"
shift 1
case $action in
    start)
        start_cmd $@
        ;;
    edit)
        edit_cmd $@
        ;;
    list)
        list_cmd
        ;;
    help)
        help_cmd
        ;;
    version)
        version_cmd
        ;;
    *)
        echo -e "Invalid command '$action'\n"
        cli_help
        ;;
esac
